### PR TITLE
React 18 support

### PR DESCRIPTION
**Pull request by saitonakamura**
Not sure if we want to merge it to main or to separate branch

### CODE REVIEW

**Review by CodyJasonBennett — APPROVED** [review]
This looks good to me although I'll want to tag what's currently master under v3 so we can backport fixes (since not everyone can migrate to React 18 just yet).

I'll want to review some of the interaction components and what we can of #76 (there's a lot going on there but I've cleaned up buttons since in #127) for 4.x.

**Comment by saitonakamura** [comment]
@CodyJasonBennett can you explain what you meant by v3 tag? Branch the current latest master into v3 branch and leave it there so we backport stuff until we eventually deprecate it for good?

**Comment by saitonakamura** [comment]
@CodyJasonBennett can you explain what you meant by v3 tag? Branch the current latest master into v3 branch and leave it there so we backport stuff until we eventually deprecate it for good?

**Comment by CodyJasonBennett** [comment]
Everything looks good here. Will see if we can bring some of the button flexibility from #76 over for v4.

**Pull request merged**
