### PR TITLE
Update to @react-three/fiber v6

### PR DESCRIPTION
**Pull request by wilcoschoneveld**
This PR updates this package with support for r3f v6.

Checklist:

- [x] Update dependencies
- [x] Fix typings and typescript errors
- [x] Make it work again
- [ ] Use three-stdlib for imports

### CODE REVIEW

**Comment by wilcoschoneveld** [comment]
Currently blocked by https://github.com/pmndrs/react-three-fiber/issues/1159

**Comment by wilcoschoneveld** [comment]
@sniok I got the VR working again with this pull request, but AR (and hittest) is broken. Could you have a look?

**Comment by sniok** [comment]
Just tried AR demo in examples folder and it works for me

**Comment by sniok** [comment]
Thank you for handling this upgrade to v6, greatly appreciated!

**Pull request merged**
