### PR TITLE
Fixing the ./examples/src/App.jsx issues

### PR DESCRIPTION
**Pull request by Soham1803**
* Installed the imported packages in ./examples/src/App.jsx issues viz: wrouter & use-error-boundary.
* Configured the eslintrc file to remove the following parsing error.
parsing-error-reactxr

### CODE REVIEW

**Comment by Soham1803** [comment]
There are still 2 warnings:
image
These could be ignored, but I wonder whether should be fixed or not?

**Comment by saitonakamura** [comment]
Hello @Soham1803 , thank you for the contribution! It's been a long-standing issue and it's great to see someone tackle it!

I've taken deliberation of fixing some stuff

* I've removed dependencies added to lib package.json. Problem was, you needed to run `yarn install` in `examples` directory to work. We don't have a Contributing guide now, so I understand it wasn't clear. Can I ask your feedback for https://github.com/pmndrs/react-xr/pull/278? Right now it's a barebone version and newcomer contributor feedback would be appreciated
* I fixed those 2 warnings in `examples/src/App.tsx`
* I've added linting examples to `yarn lint` so now CI will also warn about errors in examples 

Let me know if it works for you in current state

**Comment by saitonakamura** [comment]
> In docs, would it be a good idea to mention npm commands too, besides some developers might would directly refer to the "scripts" in package.json to run the commands.

I've added some of the scripts that will be most useful for the contributing process here https://github.com/pmndrs/react-xr/pull/278/files

> Should the packages: wouter & use-error-boundary uninstalled from lib node_modules?

For you, locally, yes. You'll just need to run `yarn` in the repo root for this

**Comment by Soham1803** [comment]
> I've added some of the scripts that will be most useful for the contributing process here https://github.com/pmndrs/react-xr/pull/278/files

Awesome, the doc looks great, with all the essential scripts mentioned.

> For you, locally, yes. You'll just need to run `yarn` in the repo root for this

Fine, got it. Thanks by the way!

I think we can proceed then...

**Pull request merged**
