### PR TITLE
added customizeable XRButton that can be used for AR/VR/Inline

### PR DESCRIPTION
**Pull request by bbohlender**
Removes the default VRButton/ARButton in exchange for a XRButton that can be placed in the dom and completely customized as it's only a HTML <button>.

Advantages:
* one Canvas to support both AR, VR and Inline sessions
* customizable enter button
* getting the current session type from the XRSessionManager (adapt to session mode)

Disadvantages:
* This requires having a XRSessionManager that provides the context. (The example page demonstrates the changes one would have to make)

The example is updated to work with both AR & VR based on the detected available session modes. (only tested using the WebXR API Emulator)

### CODE REVIEW

**Comment by cgestes** [comment]
A few noticeable things:
- the close button on the dom-overlay disappeared with this patch
- the call to setReferenceSpaceType('local') disappeared, break hit-test at the same time. (it works again when we add it back)
- it is now possible to define a custom dom overlay :)

**Comment by bbohlender** [comment]
> A few noticeable things:
> 
> * the close button on the dom-overlay disappeared with this patch
> * the call to setReferenceSpaceType('local') disappeared, break hit-test at the same time. (it works again when we add it back)
> * it is now possible to define a custom dom overlay :)

I am not quite sure whether my implementation causes the things you mention. I am afraid I did not quite catch all your points.
Maybe you can elaborate more or even give some example code, so I can better understand and reproduce the issues.
Thanks 😄

**Comment by cgestes** [comment]
for setReferenceSpaceType look at the diff of your PR.
I added something like this:
```diff
+  const setRefSpace = useCallback(() => {
+    if (xrManagerRef.current) {
+      xrManagerRef.current.setReferenceSpaceType('local')
+    }
+  }, [])

requestXRSession: async (sessionMode, sessionInit) => {
  const session = (await navigator.xr.requestSession(sessionMode, sessionInit)) as any
+ setRefSpace()
  setSession(session)

  setXRSessionInfo({ session, sessionMode, sessionInit })
}
```

the close button and overlay I reimplemented everything with react portals.

XRButton:
```jsx

const XRButton = forwardRef(({ sessionMode, sessionInit, ...props }, ref) => {
  const enterSession = useRequestXRSession()
  let opts = sessionInit?.optionalFeatures || []
  if (!opts.includes('dom-overlay')) {
    opts = [...opts, 'dom-overlay']
  }
  const overlay = getOrCreateOverlay();

  const xrSessionInfo = useXRSessionInfo();

  const onExitXR = () => {
    var element = document.getElementById("xr-overlay");
    element.style.display = "none";
  }

  useEffect(() => {
    if (xrSessionInfo == null) {
      return
    }
    xrSessionInfo.session.addEventListener('end', onExitXR)
    return () => xrSessionInfo.session.removeEventListener('end', onExitXR)
  }, [xrSessionInfo, onExitXR])



  return (
    <button
      ref={ref}
      {...props}
      onClick={() => {
        overlay.style.display = ''
        enterSession(sessionMode, {
          ...sessionInit,
          optionalFeatures: opts,
          domOverlay: { root: overlay }
        })
      }}
    />
  )
});
XRButton.displayName = "XRButton";
```

overlay:
```jsx
export const getOrCreateOverlay = () => {
  let existing = document.getElementById('xr-overlay')
  if (existing) {
    return existing
  }
  const overlay = document.createElement('div')
  overlay.setAttribute('id', 'xr-overlay')
  overlay.style.display = 'none'
  document.body.appendChild(overlay)

  return overlay
}

const Overlay = ({children}) => {
  let overlay = getOrCreateOverlay();

   return ReactDOM.createPortal(
    children,
    overlay
  );
}
```

overlay is used like this: (EnterButton is my custom XRButton)
```jsx
    <XRSessionManager>
        <XRCanvas >
        ...
        </XRCanvas>
        <EnterButton />
        <Overlay>
          <CloseButton/>
          <MenuButton onClick={onSelectMenu} />
      </Overlay>
      </XRSessionManager>
```


if there are interest I can turn all that into a PR.

**Comment by bbohlender** [comment]
> for setReferenceSpaceType look at the diff of your PR.
> I added something like this:
> 
> ```diff
> +  const setRefSpace = useCallback(() => {
> +    if (xrManagerRef.current) {
> +      xrManagerRef.current.setReferenceSpaceType('local')
> +    }
> +  }, [])
> 
> requestXRSession: async (sessionMode, sessionInit) => {
>   const session = (await navigator.xr.requestSession(sessionMode, sessionInit)) as any
> + setRefSpace()
>   setSession(session)
> 
>   setXRSessionInfo({ session, sessionMode, sessionInit })
> }
> ```
> 
> the close button and overlay I reimplemented everything with react portals.
> 
> XRButton:
> 
> ```js
> const XRButton = forwardRef(({ sessionMode, sessionInit, ...props }, ref) => {
>   const enterSession = useRequestXRSession()
>   let opts = sessionInit?.optionalFeatures || []
>   if (!opts.includes('dom-overlay')) {
>     opts = [...opts, 'dom-overlay']
>   }
>   const overlay = getOrCreateOverlay();
> 
>   const xrSessionInfo = useXRSessionInfo();
> 
>   const onExitXR = () => {
>     var element = document.getElementById("xr-overlay");
>     element.style.display = "none";
>   }
> 
>   useEffect(() => {
>     if (xrSessionInfo == null) {
>       return
>     }
>     xrSessionInfo.session.addEventListener('end', onExitXR)
>     return () => xrSessionInfo.session.removeEventListener('end', onExitXR)
>   }, [xrSessionInfo, onExitXR])
> 
> 
> 
>   return (
>     <button
>       ref={ref}
>       {...props}
>       onClick={() => {
>         overlay.style.display = ''
>         enterSession(sessionMode, {
>           ...sessionInit,
>           optionalFeatures: opts,
>           domOverlay: { root: overlay }
>         })
>       }}
>     />
>   )
> });
> XRButton.displayName = "XRButton";
> ```
> 
> overlay:
> 
> ```js
> export const getOrCreateOverlay = () => {
>   let existing = document.getElementById('xr-overlay')
>   if (existing) {
>     return existing
>   }
>   const overlay = document.createElement('div')
>   overlay.setAttribute('id', 'xr-overlay')
>   overlay.style.display = 'none'
>   document.body.appendChild(overlay)
> 
>   return overlay
> }
> 
> const Overlay = ({children}) => {
>   let overlay = getOrCreateOverlay();
> 
>    return ReactDOM.createPortal(
>     children,
>     overlay
>   );
> }
> ```
> 
> overlay is used like this: (EnterButton is my custom XRButton)
> 
> ```js
>     <XRSessionManager>
>         <XRCanvas >
>         ...
>         </XRCanvas>
>         <EnterButton />
>         <Overlay>
>           <CloseButton/>
>           <MenuButton onClick={onSelectMenu} />
>       </Overlay>
>       </XRSessionManager>
> ```
> 
> if there are interest I can turn all that into a PR.

Thanks for the clarification. I think your code is useful for most AR scenarios. However, my goal was to have a widely useable XRButton that is very extensible.
I think your usage in combination with the dom-overlay shows that the XRButton in this implementation can be very versatile.

Considering the loss of a "Close" Button in AR: This is also the case for VR. However, I think this again should be up to the developer to build, just like you did, since it can be really special to their needs.
Having an additional prebuilt close button available in this library is still probably very useful.
However, since it would depend on this PR, I would recommend implementing it only if this PR is merged since I am not sure if this PR will get merged.

**Comment by cgestes** [comment]
Yeah I agree. More composable is better.

I believe the call to setReferenceSpaceType should be addressed in this PR.

Removing the close button is a breaking change. Not sure how it should be handled.

**Comment by bbohlender** [comment]
> Yeah I agree. More composable is better.
> 
> I believe the call to setReferenceSpaceType should be addressed in this PR.
> 
> Removing the close button is a breaking change. Not sure how it should be handled.

Sorry for the late reply, I've added an ExitButton and added it to the example.

**Comment by CodyJasonBennett** [comment]
What do you think of moving the context provider to XRCanvas? We might need to [bridge context](https://docs.pmnd.rs/react-three-fiber/advanced/gotchas#consuming-context-from-a-foreign-provider) to have it work inside of R3F though.

**Comment by bbohlender** [comment]
First of all, thanks for taking the time to review the PR, I was sure this repo would pick up speed when I saw you become a maintainer ;)

Regarding your idea, I am not sure if you refer to the  "XRContext", the "XRSessionFunctionsContext" or the "XRSessionInfoContext".

I am guessing the goal is to remove the need for both
```
    <XRSessionManager>
      <XRCanvas>
```

and thus move "XRSessionFunctionsContext" and "XRSessionInfoContext" into XRCanvas. However, this is actually by design since it allows you to place the <XRSessionManager> at the root of your page, add a <XRButton> and <XRCanvas> anywhere in the dom part of the page.
The current way of splitting these two components is the best solution I could come up with to make the customization of the XRButton as simple as possible

Please correct me if I misunderstood your question :)

**Comment by CodyJasonBennett** [comment]
I see, so you'd want the buttons to be able to integrate with an existing layout, independent of the canvas. I much prefer this to the previous implementation where you'd rewrite the button anyways if you were making something with DOM access like an AR app.

Regarding the API, I'd like to move XRSession* to the XR component. The API is a little confusing as-is with multiple providers with the same dependencies and overlapping responsibility -- I think we can unify them and better split up responsibility with the XRCanvas. Similar criticisms with the hooks, I think we can derive or expose quite a bit of internal information from useXR.

I'm not sure if context is the best way to approach this, reconciler issues aside. A global store could enable ergonomic API patterns, but I'd want to explore that later. With this being a breaking change, I'd like to use the v4 milestone to iterate on top of this API. R3F v8 and improved interactions come to mind.

**Comment by bbohlender** [comment]
I must admit that I can not tell you why I've split the XRSession part in two context's, but I would guess I did not know exactly how context worked six months ago :D

Additionally, I tried to change as few as possible. However, I must agree that there's a big responsibility overlap between the XR component and the XRSessionManager.

The question for me would be whether these changes should be done in this PR or a new one and whether you are taking on this refactoring or if I should give it a try, just asking, so we don't do this redundantly.

**Comment by CodyJasonBennett** [comment]
You're free to break this up as you like, but I'd prefer to only merge once this feature is ready to ship for the sake of others.

If you need me to create a feature branch to target or work with you on a PR, I'm happy to help, but I won't do so unsolicited.

**Comment by bbohlender** [comment]
I will try to have a new version of this at the end of the week :)

**Comment by bbohlender** [comment]
I gave the task to combine all the contexts a shot and oriented the architecture on the react-three/fiber store implementation. I think there's a great potential to simplify and improve performance.
I would love to hear your feedback, and feel free to adapt my version :)

While developing, some future work tasks came to my mind:
* XRCamera (allows to "reactify" UI's etc. that bind to the camera)
* custom XRController/XRHand component as property of the XRCanvas (allows to "reactify" things that bind to the Controller/Hand like UI)
* move the xr interaction/event system into the global store

*The WebXRManager from Three.js could be recreated to work better with react. For example, three.js automatically creates two controllers ("0", "1") at the start, and they fire a "connected" event when a respective controller connects.*

**Comment by bbohlender** [comment]
@CodyJasonBennett Do you see something missing in this version regarding the initial goal and your comment (aside from fixing the merge issues)? :)

**Comment by CodyJasonBennett** [comment]
Sorry, this got missed. I'm reviewing this for v4 (R3F v8 migration), and it seems a lot is going on between modular buttons and a higher-level session API.

I'm higher on the buttons, between the two, but I'll want to break this up since it's hard to review ATM, and I may prefer to stick with native WebXR methods than some of the lighter abstractions.

**Comment by CodyJasonBennett** [comment]
Sorry for the delayed response. I'm looking at getting #131 and this across the line, although it's going to create some nasty merge conflicts. I might write to your PR a bit to clean this up and address any withstanding issues.

**Comment by CodyJasonBennett** [comment]
Continuing this in #142 which is backwards compatible via Zustand, so we can backport to v3.

**Pull request closed without merging**
